Name = 'Material.toml'
Type = 'Material'
UUID = 'af0a06bb-1f7b-411e-87af-42e435e6741b'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_diffuse.png'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_normal.png'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = 'cd0b4366-7762-489e-b6f9-10b2f55eba7a'
AmbientOcclusion = '06068709-2997-469b-a59b-a9eb274a13a1'
Metallic = '2b0698ee-d140-4609-8d6d-8f5b7a057b4b'
Normal = 'd4ab56da-f5a7-430b-a90d-1ecacc6c7b6b'
Roughness = '72279247-c03b-4a7b-9a06-f400172d29dd'

['properties.albedo']
value = [ 0.75, 0.75, 0.75, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 0.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0