Name = 'Material.toml'
Type = 'Material'
UUID = 'cc81dbb4-3907-4490-8e6a-d51d02841cbf'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_diffuse.png'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_normal.png'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '9a395858-2815-402e-95fd-b0b3af9178fe'
AmbientOcclusion = '6d687533-4285-4c5b-9d2c-029ae10ae7d1'
Metallic = '30347f7a-510b-44c1-af27-d69d5accdb30'
Normal = 'aab611e8-371a-45d2-9333-35c96d5a34f0'
Roughness = 'ef70abcc-7025-48ec-b85d-e4b938b8bae1'

['properties.albedo']
value = [ 0.75, 0.75, 0.75, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 0.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0