Name = 'Material.toml'
Type = 'Material'
UUID = 'f2bd108b-3428-4ae1-92ac-d37a3eb8587f'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_diffuse.png'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_normal.png'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '507bebe6-60ad-4875-b26a-6bee69f6e2b5'
AmbientOcclusion = 'bd1ea009-80bd-4760-8a25-8d0fe3bdc9f0'
Metallic = '3473f0fb-9c29-42b7-b010-4c10d3995736'
Normal = 'f671611f-b73a-45fb-a8a4-73045a0eddd2'
Roughness = 'e3d68e59-d331-4008-acdb-05aa55070003'

['properties.albedo']
value = [ 0.75, 0.75, 0.75, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 0.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0