Name = 'Material.toml'
Type = 'Material'
UUID = '37b2077c-d6ab-4e77-8e5c-29a667e5f785'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_diffuse.png'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_normal.png'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '8ccb1a52-a1a4-45cb-b7dc-20bd42ff5217'
AmbientOcclusion = 'a4222158-f87e-44e8-b0ad-e117e012ac76'
Metallic = '13e9d700-8ae4-4897-bd0b-d21959e838f3'
Normal = '5cc702e1-8dc6-463d-9f42-af9a7166feee'
Roughness = 'a5e3ec4d-ef33-4828-8278-305312513db3'

['properties.albedo']
value = [ 0.75, 0.75, 0.75, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 0.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0