Name = 'Material.toml'
Type = 'Material'
UUID = 'a05ad13d-3e1d-410e-bdfd-88d2a85029ea'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_diffuse.png'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_normal.png'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = 'a53aceb4-b453-4cd7-9a85-e7848f03a1ac'
AmbientOcclusion = 'cf3660c6-ddbc-4b30-b24f-75cc91b539f9'
Metallic = 'fdaaf997-abd0-4ff6-9f0a-b61ec425c2fb'
Normal = '9a50f465-59bf-405c-80d0-7fc95e72c7a6'
Roughness = '2d0e7f4c-da74-4e4b-866c-13c050a188a7'

['properties.albedo']
value = [ 0.75, 0.75, 0.75, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 0.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0