Name = 'Material.toml'
Type = 'Material'
UUID = 'fed3bf13-75bb-4e29-9b6f-ee114eb959b9'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_diffuse.png'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_normal.png'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '79d5cde5-ede3-4e61-950c-4a64674604d9'
AmbientOcclusion = '25986d85-f12b-45df-9429-68bd8029f4f9'
Metallic = '063ee9a7-facb-4e64-99d8-a703c6b9a017'
Normal = '588cc900-1d3e-41e6-9217-26822c91d766'
Roughness = '29faf59f-b792-4098-a6a4-b64f2b7a9449'

['properties.albedo']
value = [ 0.75, 0.75, 0.75, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 0.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0