Name = 'Material.toml'
Type = 'Material'
UUID = '49a07861-5f34-4f7e-82a6-126c400577e3'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_diffuse.png'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_normal.png'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = 'e6fd6fc2-261b-4f2f-9266-87d90e05abc6'
AmbientOcclusion = 'dafced82-671f-4d2a-9e9e-5c25ecc263b7'
Metallic = '43e2a57f-28cc-4beb-a1c0-a80818c0ee78'
Normal = 'fbcd4a2e-0456-45bf-b296-60bdf6069edc'
Roughness = 'f0785ec5-877b-4017-ac68-ee2afa40944c'

['properties.albedo']
value = [ 0.75, 0.75, 0.75, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 0.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0