Name = 'Material.toml'
Type = 'Material'
UUID = '8a8c36cf-4dbe-4123-b987-621b37865096'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_diffuse.png'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_normal.png'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '8e9b5b22-eb18-4c06-a6ab-a5566724a833'
AmbientOcclusion = '1dc50835-1dab-43a8-8e51-857085c70e49'
Metallic = 'eb200475-3855-4315-880a-4b96fe575974'
Normal = 'e1aca359-ac48-42a6-96a6-634f32066038'
Roughness = '670e18da-88e4-47c8-8f23-f25ffb717ebe'

['properties.albedo']
value = [ 0.75, 0.75, 0.75, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 0.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0