Name = 'Material.toml'
Type = 'Material'
UUID = '7eea22cd-7b7d-46a7-84ca-ec7468cb1dfd'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_diffuse.png'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_normal.png'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '56eb314e-b623-40b0-8d86-ed52004c2cec'
AmbientOcclusion = '6e27bbc8-b9ae-47c1-a3ff-d07bf5159789'
Metallic = '5623aac2-59a6-4a8c-8122-67613a5531f1'
Normal = '8fc4dc53-3617-4b2f-9fdb-93efb79b7214'
Roughness = '34165f07-b343-4d2e-bebf-cd28aa0edbf1'

['properties.albedo']
value = [ 0.75, 0.75, 0.75, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 0.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0