Name = 'Material.toml'
Type = 'Material'
UUID = '85476e49-1621-43a5-bd6a-fa5789d70e6b'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_diffuse.png'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_normal.png'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '589e00ee-f06d-47e4-b45c-bcfa82a175ea'
AmbientOcclusion = '1982735f-e798-4845-8897-a7b9b8d79388'
Metallic = '2a939be5-b3c5-467c-9e61-805ac158fb58'
Normal = '583ba526-ce0f-4922-98a1-3977d4223786'
Roughness = '3c6b60da-ffb1-4396-842f-8f919676cbc9'

['properties.albedo']
value = [ 0.75, 0.75, 0.75, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 0.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0