Name = 'Material.toml'
Type = 'Material'
UUID = '08903ebb-5414-4f3c-9af8-add844925665'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_diffuse.png'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_normal.png'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '850253b5-518e-4d25-9ce1-a1111df4dad0'
AmbientOcclusion = '24b3d1ee-28ea-4d28-abb0-47110655313a'
Metallic = '1c4cd9a1-5072-466b-92f6-cdca91fbac97'
Normal = 'b37f94b2-ca35-4f4c-a2fc-993e4eaf765b'
Roughness = '145dd408-a310-449b-a706-c1171a1fda74'

['properties.albedo']
value = [ 0.75, 0.75, 0.75, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 0.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0