Name = 'Material.toml'
Type = 'Material'
UUID = 'a83d20c6-663b-4e40-b2c4-836467852d06'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_diffuse.png'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_normal.png'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '7f5c652d-a03f-4ccd-a6b7-cabcf360c427'
AmbientOcclusion = 'f901f564-ddcf-4150-a88b-9d2e5e6cfdc4'
Metallic = '52201a66-197c-4b40-9680-238f0fcde7dc'
Normal = 'f3df01cf-8f1a-41b6-b622-bc4ececf23b8'
Roughness = 'fc530369-2141-46c2-a9a2-9d062941ee56'

['properties.albedo']
value = [ 0.75, 0.75, 0.75, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 0.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0