Name = 'Material.toml'
Type = 'Material'
UUID = '4bda629b-4c4b-41d3-a7bd-9ebee6dff12c'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_diffuse.png'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_normal.png'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '8fcc9047-9255-419f-a2c4-2deae4f83b5c'
AmbientOcclusion = '1110ee28-1384-4302-9f24-c827f50bd54d'
Metallic = 'e37bfc78-5b65-4aa7-a4be-470e05431ddf'
Normal = 'e12689b0-a4d0-41ee-b173-4b4254f9a4c9'
Roughness = '0ce90ec2-5900-4046-a83c-d0dc3080c3c8'

['properties.albedo']
value = [ 0.75, 0.75, 0.75, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 0.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0