Name = 'Material.toml'
Type = 'Material'
UUID = 'c5c2ce23-1d67-4c80-9f64-ac772627d3ac'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_diffuse.png'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_normal.png'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '43a555f8-7475-49ae-8765-7aaf5084ffc4'
AmbientOcclusion = '7c648b0f-3974-4e17-b932-86b547710e27'
Metallic = 'b126a381-c13c-4f1e-b73e-fd8853d93ba3'
Normal = 'f2682f2b-5d2f-4ec1-b550-96af5884e4ff'
Roughness = 'be8b05b1-b26a-4ad4-8f4a-f228049a7bf9'

['properties.albedo']
value = [ 0.75, 0.75, 0.75, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 0.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0