Name = 'Material.toml'
Type = 'Material'
UUID = '5187c963-c60e-4d31-aba4-8edb80d288cb'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_diffuse.png'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_normal.png'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '37a1e0bd-0002-4bab-9d4a-d199084ade56'
AmbientOcclusion = '09981f13-c283-4dda-b29d-76fd421cad19'
Metallic = 'c91f3b42-623d-4d9b-ae99-d51a16574234'
Normal = 'b1514c5f-734a-4c47-9d2a-f83c398aca9c'
Roughness = 'fb1bb8c9-a428-4261-a2c4-cb76eb8e2d73'

['properties.albedo']
value = [ 0.75, 0.75, 0.75, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 0.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0