Name = 'Material.toml'
Type = 'Material'
UUID = 'f4ff830c-81f6-4014-a761-a86a0ead49f6'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_diffuse.png'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_normal.png'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = 'ff714ad9-5bd9-482a-810b-5e72feb52923'
AmbientOcclusion = '4abbc854-eb75-4259-b4d5-09efb539481a'
Metallic = '0db7eb76-81c5-4c21-817e-06a6d65ead42'
Normal = '9de30443-325a-495b-9741-d2cf3e422f57'
Roughness = 'b8b034b4-fa22-49ea-8b72-bb3cfb341186'

['properties.albedo']
value = [ 0.75, 0.75, 0.75, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 0.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0