Name = 'arch.toml'
Type = 'Material'
UUID = 'ed18260d-49d6-4b4e-8bad-541a4c8089a5'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_arch_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_arch_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = 'bac8fa7e-522c-4c50-bd4a-215e88da2cd6'
AmbientOcclusion = 'd516c30e-1a00-4332-93a7-00842791a762'
Metallic = '168f340c-4a48-4262-a73a-f0cd35439a59'
Normal = 'b141caf6-002a-4390-9ead-15b9875d44ff'
Roughness = '2481bd11-a2f0-40e4-8d00-80ecd6eaa291'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0