Name = 'bricks.toml'
Type = 'Material'
UUID = '8b133af5-c442-41d0-b086-6df29fb12502'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/spnza_bricks_a_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/spnza_bricks_a_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '0c131d03-8bde-4f59-9955-6dbed32914c2'
AmbientOcclusion = 'fdbb43cf-82ac-489b-b38f-fa40b76aa7cc'
Metallic = '1bf2cae4-4cbe-4640-ac3b-ed83c31120d8'
Normal = '0317e9e2-b281-439e-a5e1-d2c95fb205e1'
Roughness = '1957f4f1-aa48-450b-b2d3-0b7894f55581'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0