Name = 'bricks.toml'
Type = 'Material'
UUID = '81d96f28-7e74-4273-8a32-93c7af9da2a3'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/spnza_bricks_a_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/spnza_bricks_a_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = 'a3bcca03-2c16-4253-9979-6b706b2414b1'
AmbientOcclusion = '7532dd13-83da-4fbb-9a23-0ab740591f96'
Metallic = '51f2f464-0d82-4d89-b2c2-ef646140de57'
Normal = '7d5f75fc-78f6-47f8-b8dc-a292a19bcf40'
Roughness = 'e70366ec-b9c9-4016-8209-428f80253fb3'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0