Name = 'ceiling.toml'
Type = 'Material'
UUID = 'e6708662-21f5-4615-bdb9-81dc422fe692'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_ceiling_a_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_ceiling_a_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = 'cd3bc697-465f-451c-875d-8e54295fbfcb'
AmbientOcclusion = '7c648b0f-3974-4e17-b932-86b547710e27'
Metallic = 'b126a381-c13c-4f1e-b73e-fd8853d93ba3'
Normal = '179fef41-c7fb-4047-a8c9-4757e8b40f07'
Roughness = 'be8b05b1-b26a-4ad4-8f4a-f228049a7bf9'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0