Name = 'column_c.toml'
Type = 'Material'
UUID = 'f35e0f29-8dd4-45de-9761-a5355c4c210c'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_column_c_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_column_c_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '0a25cde5-1a4b-494a-be09-0020102fc22d'
AmbientOcclusion = '9218116a-a526-48d9-9218-b36f869068c6'
Metallic = 'ef1e4911-ac09-408d-9fe2-dd5d255caa40'
Normal = '47d56e47-fbf1-4bfb-b44b-19f2c06c906c'
Roughness = 'd6ef4333-62e5-49d4-a3e1-62d1dc36bcaf'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0