Name = 'column_b.toml'
Type = 'Material'
UUID = 'e3607650-07ee-4bba-96be-d6d1c2104094'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_column_b_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_column_b_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = 'cc9b7dc2-6ebd-4ff6-adba-9083c24e2963'
AmbientOcclusion = '443c3376-43fb-45fa-ac7b-c8254e6e3fe1'
Metallic = '9fe7c8ff-a6e7-4837-882d-99ac1a2a98be'
Normal = '7de57fba-c156-4a06-9bca-4f5d4a2ad279'
Roughness = '429045a2-9012-4811-8b0b-834064d64f89'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0