Name = 'column_a.toml'
Type = 'Material'
UUID = '69c7daba-7ffc-4459-8226-ed1b7d5a24c3'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_column_a_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_column_a_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = 'b3575f8c-72b9-4368-ba3c-eb410f1f1d3f'
AmbientOcclusion = 'fdbb43cf-82ac-489b-b38f-fa40b76aa7cc'
Metallic = '1bf2cae4-4cbe-4640-ac3b-ed83c31120d8'
Normal = '8c1356de-130d-4b77-8ea2-6e838decb4ce'
Roughness = '1957f4f1-aa48-450b-b2d3-0b7894f55581'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0