Name = 'column_a.toml'
Type = 'Material'
UUID = 'd4a3e8e9-e222-4346-bf6c-db41b7951eb1'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_column_a_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_column_a_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '41651ef5-f416-4b49-9599-c71a7f021a08'
AmbientOcclusion = '7c648b0f-3974-4e17-b932-86b547710e27'
Metallic = 'b126a381-c13c-4f1e-b73e-fd8853d93ba3'
Normal = '81b6602e-50f6-41d4-9b60-21d5fdd9c6a3'
Roughness = 'be8b05b1-b26a-4ad4-8f4a-f228049a7bf9'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0