Name = 'column_a.toml'
Type = 'Material'
UUID = '0a94861c-905d-47a8-a32d-034e8c530660'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_column_a_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_column_a_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '7c02e75b-1384-41c7-a4e7-c12b860afda1'
AmbientOcclusion = '9218116a-a526-48d9-9218-b36f869068c6'
Metallic = 'ef1e4911-ac09-408d-9fe2-dd5d255caa40'
Normal = '5c50224d-bcfe-47fc-b959-ee741fa3f069'
Roughness = 'd6ef4333-62e5-49d4-a3e1-62d1dc36bcaf'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0