Name = 'column_a.toml'
Type = 'Material'
UUID = 'be995891-dfae-49df-a5df-159a456fdd88'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_column_a_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_column_a_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '06151d44-698d-4988-869d-cb4d66d5ed84'
AmbientOcclusion = 'e017429a-4f3d-484f-80e6-db3b467423cf'
Metallic = '917023cc-8912-406f-b4dd-b9f98b81e821'
Normal = '0c778623-af78-4970-96a2-b5b16818a688'
Roughness = 'ae673f67-7b5e-4fb4-88a7-9c90a9f42169'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0