Name = 'DefaultMaterial.toml'
Type = 'Material'
UUID = 'd1ed2be7-8406-48b5-b9fa-5fbf2e439f55'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_diffuse.png'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_normal.png'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '8ebe0d46-1271-41d7-a0c9-154ff145130b'
AmbientOcclusion = '9218116a-a526-48d9-9218-b36f869068c6'
Metallic = 'ef1e4911-ac09-408d-9fe2-dd5d255caa40'
Normal = '8667ea19-95b2-4642-8148-30ab8ca6f989'
Roughness = 'd6ef4333-62e5-49d4-a3e1-62d1dc36bcaf'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0