Name = 'details.toml'
Type = 'Material'
UUID = 'd45e2919-f7f5-4818-8bce-77b1947b7adb'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_details_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_details_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '1df5aa09-a375-4c3e-9f17-87617c3dcfc0'
AmbientOcclusion = 'd516c30e-1a00-4332-93a7-00842791a762'
Metallic = '168f340c-4a48-4262-a73a-f0cd35439a59'
Normal = '9c017762-ae97-4330-9d1b-f2c38cfe8d35'
Roughness = '2481bd11-a2f0-40e4-8d00-80ecd6eaa291'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0