Name = 'details.toml'
Type = 'Material'
UUID = '645171c8-8526-44c5-9039-f1879e4be52b'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_details_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_details_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = 'd9c8bbf2-09ae-4447-93b3-13460d0d08ea'
AmbientOcclusion = '9218116a-a526-48d9-9218-b36f869068c6'
Metallic = 'ef1e4911-ac09-408d-9fe2-dd5d255caa40'
Normal = '19449fe8-9281-4609-b048-106a40e0d196'
Roughness = 'd6ef4333-62e5-49d4-a3e1-62d1dc36bcaf'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0