Name = 'fabric_f.toml'
Type = 'Material'
UUID = '3f09496c-9445-446e-830c-82c36ee3af68'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_curtain_green_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_curtain_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '3fbfc747-bcf0-406f-bf71-697e009522d7'
AmbientOcclusion = '7532dd13-83da-4fbb-9a23-0ab740591f96'
Metallic = '51f2f464-0d82-4d89-b2c2-ef646140de57'
Normal = '858ff23b-f7d6-4ce2-b9ea-9ed0fb5bf236'
Roughness = 'e70366ec-b9c9-4016-8209-428f80253fb3'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0