Name = 'fabric_g.toml'
Type = 'Material'
UUID = 'f82c3011-3b70-4eb7-9f5e-da71596d4794'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_curtain_blue_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_curtain_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '1e66ac8e-2bc1-4edf-bf1b-555a2ac8ccac'
AmbientOcclusion = 'd516c30e-1a00-4332-93a7-00842791a762'
Metallic = '168f340c-4a48-4262-a73a-f0cd35439a59'
Normal = 'f72cfeef-4247-41ea-872b-55e46e4db288'
Roughness = '2481bd11-a2f0-40e4-8d00-80ecd6eaa291'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0