Name = 'fabric_g.toml'
Type = 'Material'
UUID = '419d8d52-bd47-4acb-a47e-64dbe749ef0c'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_curtain_blue_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_curtain_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '7001b779-1606-455a-bffe-ca13a2653cd6'
AmbientOcclusion = 'fdbb43cf-82ac-489b-b38f-fa40b76aa7cc'
Metallic = '1bf2cae4-4cbe-4640-ac3b-ed83c31120d8'
Normal = '6b52837b-a9f8-42d5-afb8-088ddf31a8e4'
Roughness = '1957f4f1-aa48-450b-b2d3-0b7894f55581'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0