Name = 'fabric_e.toml'
Type = 'Material'
UUID = 'e52d9a39-dfe9-4751-a2c5-5e981ef18f87'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_fabric_green_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_fabric_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '93f800c4-0248-443c-beed-18de3a72ef8a'
AmbientOcclusion = 'e017429a-4f3d-484f-80e6-db3b467423cf'
Metallic = '917023cc-8912-406f-b4dd-b9f98b81e821'
Normal = '5ddc8808-674a-4cd7-ad69-fc40a278cb20'
Roughness = 'ae673f67-7b5e-4fb4-88a7-9c90a9f42169'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0