Name = 'fabric_c.toml'
Type = 'Material'
UUID = 'bf7a345f-6531-4ef6-9282-a09bd53d69c8'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_curtain_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_curtain_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = 'e2e1ebf0-1659-4bee-8518-f51bcae0fb38'
AmbientOcclusion = '7532dd13-83da-4fbb-9a23-0ab740591f96'
Metallic = '51f2f464-0d82-4d89-b2c2-ef646140de57'
Normal = '858ff23b-f7d6-4ce2-b9ea-9ed0fb5bf236'
Roughness = 'e70366ec-b9c9-4016-8209-428f80253fb3'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0