Name = 'fabric_e.toml'
Type = 'Material'
UUID = '35f78feb-712f-4414-b420-e380d6b0e3e6'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_fabric_green_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_fabric_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '71698a9f-94b0-4c85-a620-8475b2eb1f17'
AmbientOcclusion = '9218116a-a526-48d9-9218-b36f869068c6'
Metallic = 'ef1e4911-ac09-408d-9fe2-dd5d255caa40'
Normal = 'afeea9d5-ee60-4f70-840f-7555f1a78bc3'
Roughness = 'd6ef4333-62e5-49d4-a3e1-62d1dc36bcaf'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0