Name = 'flagpole.toml'
Type = 'Material'
UUID = 'a27d4530-4d24-400e-8626-ba6e1579e833'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_flagpole_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_flagpole_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '213f53ab-efb3-4126-bbac-2dca3ebe951d'
AmbientOcclusion = '443c3376-43fb-45fa-ac7b-c8254e6e3fe1'
Metallic = '9fe7c8ff-a6e7-4837-882d-99ac1a2a98be'
Normal = '8ce09af5-e673-4aa5-9f9f-84bda08c327e'
Roughness = '429045a2-9012-4811-8b0b-834064d64f89'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0