Name = 'flagpole.toml'
Type = 'Material'
UUID = '1ae04bcc-994a-489a-af71-1138704f0ec2'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_flagpole_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_flagpole_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = 'edf7b023-fe92-4157-a8fa-f89b151c5700'
AmbientOcclusion = '7532dd13-83da-4fbb-9a23-0ab740591f96'
Metallic = '51f2f464-0d82-4d89-b2c2-ef646140de57'
Normal = 'ec463982-45fb-4c47-be14-d9e241833541'
Roughness = 'e70366ec-b9c9-4016-8209-428f80253fb3'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0