Name = 'floor.toml'
Type = 'Material'
UUID = '750eee47-772a-4b04-a18c-87e67c23cd0c'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_floor_a_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_floor_a_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = 'b98c6134-d965-4ae0-99db-0e07a7b2d42d'
AmbientOcclusion = '7532dd13-83da-4fbb-9a23-0ab740591f96'
Metallic = '51f2f464-0d82-4d89-b2c2-ef646140de57'
Normal = '5a276e54-6513-49f0-a9a8-ff61f7cf766c'
Roughness = 'e70366ec-b9c9-4016-8209-428f80253fb3'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0