Name = 'floor.toml'
Type = 'Material'
UUID = '541074cb-32c4-49e5-be75-d7dcefffc80c'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_floor_a_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_floor_a_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = 'd683cd26-58c7-45a0-a4e1-72c41dbb14db'
AmbientOcclusion = 'fdbb43cf-82ac-489b-b38f-fa40b76aa7cc'
Metallic = '1bf2cae4-4cbe-4640-ac3b-ed83c31120d8'
Normal = '64d5526b-b9ac-4df0-a65a-4311e66ed5ec'
Roughness = '1957f4f1-aa48-450b-b2d3-0b7894f55581'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0