Name = 'floor.toml'
Type = 'Material'
UUID = 'e30ede83-d297-4d8e-b001-ea1b9fb53433'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_floor_a_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_floor_a_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '11e6be3e-f4ea-42b2-b657-411e6fecea4f'
AmbientOcclusion = '443c3376-43fb-45fa-ac7b-c8254e6e3fe1'
Metallic = '9fe7c8ff-a6e7-4837-882d-99ac1a2a98be'
Normal = 'dd96b859-2e2b-4b52-9ed0-212d5c3f5b6a'
Roughness = '429045a2-9012-4811-8b0b-834064d64f89'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0