Name = 'leaf.toml'
Type = 'Material'
UUID = 'ea37139e-f36a-4409-88d4-cb328ef10579'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_thorn_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_thorn_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = 'cd7e956f-276c-479b-8d51-38a4e9cd396b'
AmbientOcclusion = 'e017429a-4f3d-484f-80e6-db3b467423cf'
Metallic = '917023cc-8912-406f-b4dd-b9f98b81e821'
Normal = '17f799ce-031b-4be5-9bf1-bf0f87ef3b4d'
Roughness = 'ae673f67-7b5e-4fb4-88a7-9c90a9f42169'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0