Name = 'M_Arch_Inst.toml'
Type = 'Material'
UUID = '635ddc6e-a38a-46e7-99e5-faa140577252'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Arch_Inst_0_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Arch_Inst_0_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Arch_Inst_0_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Arch_Inst_0_Specular.dds'

['dependencies.uuid']
Albedo = '690716a5-66af-48cd-b2f6-1e280d936c95'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = '08d31cb3-4dd4-48ca-86fd-52c8f5b650bc'
Normal = '28b4a0ae-e3e4-482b-8e31-97c4d5e175e5'
Roughness = '08d31cb3-4dd4-48ca-86fd-52c8f5b650bc'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0