Name = 'M_Arch_Inst_Red.toml'
Type = 'Material'
UUID = '0cc9c606-81fc-4f4d-9962-24054ff18af7'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Arch_Inst_Red_0_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Arch_Inst_Red_0_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Arch_Inst_Red_0_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Arch_Inst_Red_0_Specular.dds'

['dependencies.uuid']
Albedo = '56ccff39-455e-4461-a50e-7e1dd9c69c0f'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = 'b77fdfe6-501e-418a-85e7-d67f9f14d56d'
Normal = 'f810a77d-c0b2-4c3e-8b6c-b32802a3f0cc'
Roughness = 'b77fdfe6-501e-418a-85e7-d67f9f14d56d'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0