Name = 'M_BottomTrim_Inst_UTile4.toml'
Type = 'Material'
UUID = '0a2779b1-5036-48d8-a4a7-1765abd36d69'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_BottomTrim_Inst_UTile4_0_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_BottomTrim_Inst_UTile4_0_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_BottomTrim_Inst_UTile4_0_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_BottomTrim_Inst_UTile4_0_Specular.dds'

['dependencies.uuid']
Albedo = '79f96a9f-02d7-4fa0-882a-ad60d977b896'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = 'b67f371b-ca8f-440c-99bf-099c57e97f66'
Normal = '2d966bdd-e0e0-429f-beeb-10794e1b6599'
Roughness = 'b67f371b-ca8f-440c-99bf-099c57e97f66'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0