Name = 'M_BottomTrim_Inst.toml'
Type = 'Material'
UUID = '829001bf-e27b-440f-9daf-8b499843ee29'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_BottomTrim_Inst_0_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_BottomTrim_Inst_0_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_BottomTrim_Inst_0_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_BottomTrim_Inst_0_Specular.dds'

['dependencies.uuid']
Albedo = 'adc080cd-ccb0-4560-8e9e-4f4485938aa9'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = '87ca0d66-9695-4b44-bb18-79171798ff2c'
Normal = '6b012401-5858-451b-9061-0b2eeaa512f9'
Roughness = '87ca0d66-9695-4b44-bb18-79171798ff2c'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0