Name = 'M_BottomTrim_Inst_Black.toml'
Type = 'Material'
UUID = 'ac75675d-8277-487d-80fa-97bf2f8836c4'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_BottomTrim_Inst_Black_0_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_BottomTrim_Inst_Black_0_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_BottomTrim_Inst_Black_0_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_BottomTrim_Inst_Black_0_Specular.dds'

['dependencies.uuid']
Albedo = '1c024ac2-cf49-4f5d-9fd7-203da4a41f83'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = '6b37eb43-8b40-4602-abfa-510e2b096667'
Normal = 'd9053882-f407-4402-9cc7-a4949f5b9242'
Roughness = '6b37eb43-8b40-4602-abfa-510e2b096667'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0