Name = 'M_Dome_Inst.toml'
Type = 'Material'
UUID = 'ed55cc3e-b961-4bdf-827d-d9cb0fa05175'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Dome_Inst_0_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Dome_Inst_0_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Dome_Inst_0_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Dome_Inst_0_Specular.dds'

['dependencies.uuid']
Albedo = '90a9a9b9-1f55-4ebb-b99e-133e0486bc1f'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = '81056e41-b2d1-4508-9523-485c2c8ad0c9'
Normal = 'cc0b2960-f305-40e4-8daf-69bfa9f97e53'
Roughness = '81056e41-b2d1-4508-9523-485c2c8ad0c9'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0