Name = 'M_Dome_2.toml'
Type = 'Material'
UUID = '349defa6-b1c0-4262-a063-baf24baa8d59'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Dome_2_0_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Dome_2_0_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Dome_2_0_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Dome_2_0_Specular.dds'

['dependencies.uuid']
Albedo = '66e05944-7031-48f6-8ef5-d8a33f28f46b'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = '6b56c2c6-1086-4847-83b9-6915e5125796'
Normal = 'f481f282-963b-4aa3-a003-965be1e46914'
Roughness = '6b56c2c6-1086-4847-83b9-6915e5125796'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0