Name = 'M_FirePit_Inst_Glow.toml'
Type = 'Material'
UUID = '292800cb-cfa5-4773-8799-94894437bbc9'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_FirePit_Inst_Glow_0_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_FirePit_Inst_Glow_0_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_FirePit_Inst_Glow_0_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_FirePit_Inst_Glow_0_Specular.dds'

['dependencies.uuid']
Albedo = '88157c54-a852-447a-9f6b-92d9bb285cc9'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = '3447f9e0-e509-463c-a049-72437feb0bbb'
Normal = '93241733-55f5-4edf-a08f-b0befb3097ba'
Roughness = '3447f9e0-e509-463c-a049-72437feb0bbb'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0