Name = 'M_FirePit_Inst_nofire.toml'
Type = 'Material'
UUID = 'cf43a53f-feb0-4475-aeae-16b7e65143e8'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_FirePit_Inst_nofire_0_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_FirePit_Inst_nofire_0_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_FirePit_Inst_nofire_0_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_FirePit_Inst_nofire_0_Specular.dds'

['dependencies.uuid']
Albedo = 'ade0aa15-d878-4422-be39-cbda61816a31'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = 'd8824430-27e7-4800-a0a4-f6d597b32dda'
Normal = '85867b53-d15a-4d35-9ed2-973b42d49c94'
Roughness = 'd8824430-27e7-4800-a0a4-f6d597b32dda'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0