Name = 'M_FirePit_Inst.toml'
Type = 'Material'
UUID = '35ace4e0-c7f4-4bc4-8eaa-fd1c8372dd03'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_FirePit_Inst_0_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_FirePit_Inst_0_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_FirePit_Inst_0_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_FirePit_Inst_0_Specular.dds'

['dependencies.uuid']
Albedo = '7ad71da8-559b-4b3e-997f-73c4dda9754f'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = '439c447c-8c96-43d4-8f52-90bede93d579'
Normal = '70d04fb7-0248-4b9d-83c8-02f884d855b9'
Roughness = '439c447c-8c96-43d4-8f52-90bede93d579'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0