Name = 'M_FloorTiles1_Inst_Inst2.toml'
Type = 'Material'
UUID = '975f6323-4df1-4d18-8f2a-1c116d3f92e5'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_FloorTiles1_Inst_Inst2_0_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_FloorTiles1_Inst_Inst2_0_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_FloorTiles1_Inst_Inst2_0_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_FloorTiles1_Inst_Inst2_0_Specular.dds'

['dependencies.uuid']
Albedo = 'bef5ee50-7387-407b-bfdc-ff08895a47f7'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = 'c53bd5b9-a1da-44a4-9925-86984ccc306f'
Normal = '0a1a3d5b-b2c3-48bb-9df2-bebb8c192d92'
Roughness = 'c53bd5b9-a1da-44a4-9925-86984ccc306f'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0