Name = 'M_FloorTiles1_Inst.toml'
Type = 'Material'
UUID = '35282b69-0a65-4ced-a772-860537f27c87'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_FloorTiles1_Inst_0_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_FloorTiles1_Inst_0_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_FloorTiles1_Inst_0_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_FloorTiles1_Inst_0_Specular.dds'

['dependencies.uuid']
Albedo = '9c9e73f5-6b04-4ac0-b6e3-48613348bae0'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = '9e21deb7-3d47-4e6f-9e1c-1af727c80233'
Normal = 'd2a74cf6-d863-4638-96e5-0adfa090305a'
Roughness = '9e21deb7-3d47-4e6f-9e1c-1af727c80233'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0