Name = 'M_Pillar_Inst_Colored.toml'
Type = 'Material'
UUID = '161d851b-53f7-492a-ac32-4b6bc18a6a59'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Pillar_Inst_Colored_0_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Pillar_Inst_Colored_0_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Pillar_Inst_Colored_0_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Pillar_Inst_Colored_0_Specular.dds'

['dependencies.uuid']
Albedo = '6eaa1776-2956-48a8-83ad-e95c69b6dbe5'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = '286d338f-cbfb-4833-93cb-9abba1e132a9'
Normal = '96fe150f-1120-4e57-b2c0-ff3428dc2b2a'
Roughness = '286d338f-cbfb-4833-93cb-9abba1e132a9'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0