Name = 'M_Railing_Inst.toml'
Type = 'Material'
UUID = '8a4e405f-6066-4d68-8402-7fa87caa28cb'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Railing_Inst_0_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Railing_Inst_0_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Railing_Inst_0_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Railing_Inst_0_Specular.dds'

['dependencies.uuid']
Albedo = '1e127ee4-6ba9-4778-8c33-1a8faab49c74'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = 'a6906a91-fe89-44a0-b5ed-2d3e40963645'
Normal = '3a0b04de-10dc-4571-b544-ca2a4716a92a'
Roughness = 'a6906a91-fe89-44a0-b5ed-2d3e40963645'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0