Name = 'M_Rocks_Inst.toml'
Type = 'Material'
UUID = '0dc92063-b40b-4804-8173-8ec7a92f7230'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Rocks_Inst_2_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Rocks_Inst_2_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Rocks_Inst_2_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Rocks_Inst_2_Specular.dds'

['dependencies.uuid']
Albedo = '11f537f9-2a97-4c64-b4ba-b0a796753ccb'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = '6977c2be-ad25-4659-ab18-d70c93e3e33f'
Normal = '0ab6eee2-2a60-487c-bd8c-dac7db9c7ab9'
Roughness = '6977c2be-ad25-4659-ab18-d70c93e3e33f'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0