Name = 'M_Rocks_Inst.002.toml'
Type = 'Material'
UUID = 'fd68a073-6b22-4bef-8282-f7be8aa1a588'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Rocks_Inst_0_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Rocks_Inst_0_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Rocks_Inst_0_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Rocks_Inst_0_Specular.dds'

['dependencies.uuid']
Albedo = '5360ec2f-59b2-4dfb-b63a-a8f1bf655c2a'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = '5080000d-653a-4c31-9d6a-45f697f83b54'
Normal = 'd778a2c0-fa2a-4ba6-94d1-eea53c4c0ca1'
Roughness = '5080000d-653a-4c31-9d6a-45f697f83b54'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0