Name = 'M_Shield_Inst.toml'
Type = 'Material'
UUID = 'eb7a00a9-e20e-497e-8d4a-39a86b6459ab'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Shield_Inst_0_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Shield_Inst_0_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Shield_Inst_0_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Shield_Inst_0_Specular.dds'

['dependencies.uuid']
Albedo = '7f45dc73-8a38-4ab2-8240-1e7a23e6daf7'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = 'fc9a1522-1734-435a-8cc8-badf6ba252f3'
Normal = 'b758ddbe-bbd6-4d23-9503-a69f052c177b'
Roughness = 'fc9a1522-1734-435a-8cc8-badf6ba252f3'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0