Name = 'M_Soul_Rocks2_Inst.001.toml'
Type = 'Material'
UUID = '1a07bd73-d83a-49ba-8363-3114b07977b9'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Soul_Rocks2_Inst_11_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Soul_Rocks2_Inst_11_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Soul_Rocks2_Inst_11_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Soul_Rocks2_Inst_11_Specular.dds'

['dependencies.uuid']
Albedo = '9a826cb0-3cbd-40ca-9ecb-c75405f52981'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = 'fbc60bec-0832-4d37-acf8-9d45a4a39fc9'
Normal = '53c8328f-7c95-4a1d-878b-0a114d2ca68f'
Roughness = 'fbc60bec-0832-4d37-acf8-9d45a4a39fc9'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0