Name = 'M_Soul_Rocks2_Inst.008.toml'
Type = 'Material'
UUID = '606e375d-8379-4701-8a65-42b7a449275f'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Soul_Rocks2_Inst_4_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Soul_Rocks2_Inst_4_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Soul_Rocks2_Inst_4_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Soul_Rocks2_Inst_4_Specular.dds'

['dependencies.uuid']
Albedo = '61706f72-639e-48d7-af48-a0db7da1c39e'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = '7819f7e0-b0ae-42d1-b58a-c99d4babe520'
Normal = '29c2210d-58bd-4273-9de6-b01f0d1cc6a2'
Roughness = '7819f7e0-b0ae-42d1-b58a-c99d4babe520'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0