Name = 'M_Soul_Rocks2_Inst.011.toml'
Type = 'Material'
UUID = '5322b0ac-5f40-4bd7-b7ff-cf0dfa3c3213'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Soul_Rocks2_Inst_1_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Soul_Rocks2_Inst_1_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Soul_Rocks2_Inst_1_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Soul_Rocks2_Inst_1_Specular.dds'

['dependencies.uuid']
Albedo = '6c72e1ac-7855-45cf-8ac8-0be37a53587a'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = '1d590451-40ac-4efc-8d99-982869628101'
Normal = '04e9db12-8141-44bc-9911-1969a568a0d9'
Roughness = '1d590451-40ac-4efc-8d99-982869628101'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0