Name = 'M_StoneBrickWall_Inst.toml'
Type = 'Material'
UUID = '21b96c4f-3b10-4032-9745-10365d610be2'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_StoneBrickWall_Inst_0_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_StoneBrickWall_Inst_0_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_StoneBrickWall_Inst_0_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_StoneBrickWall_Inst_0_Specular.dds'

['dependencies.uuid']
Albedo = 'bd964492-7c6a-40f3-9eb7-a456fd60bc1a'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = '55792b52-78c7-4a39-8a0b-44f7b435a467'
Normal = 'b0957bb7-04fe-4201-812f-8f93a5d976c1'
Roughness = '55792b52-78c7-4a39-8a0b-44f7b435a467'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0