Name = 'M_Statue_Inst.toml'
Type = 'Material'
UUID = '578e2a35-b595-4bc0-af46-89b8ecf679be'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Statue_Inst_0_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Statue_Inst_0_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Statue_Inst_0_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Statue_Inst_0_Specular.dds'

['dependencies.uuid']
Albedo = '83508dfb-a626-4164-a53e-5db4ed690177'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = '3eb7cbd6-9f05-4bd7-9f08-3e227325d46c'
Normal = '88f5d581-e0e8-4a0d-a6be-fd15977fcd82'
Roughness = '3eb7cbd6-9f05-4bd7-9f08-3e227325d46c'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0