Name = 'M_Stairs_Inst.toml'
Type = 'Material'
UUID = '0ecd4268-3b07-4c55-a84d-ba1c6e043a1f'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Stairs_Inst_0_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Stairs_Inst_0_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Stairs_Inst_0_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Stairs_Inst_0_Specular.dds'

['dependencies.uuid']
Albedo = 'eee6c225-cb94-4cce-9678-973ad66290d1'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = '6ee51ee8-f791-473c-acce-fd5b7a62ab52'
Normal = '5ca05d11-6880-40a5-8dfd-c489f79e5759'
Roughness = '6ee51ee8-f791-473c-acce-fd5b7a62ab52'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0