Name = 'M_Trim_Inst_Inst.toml'
Type = 'Material'
UUID = '3638fd98-a64a-45bd-8b1d-1407c76617a9'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Trim_Inst_Inst_0_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Trim_Inst_Inst_0_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Trim_Inst_Inst_0_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Trim_Inst_Inst_0_Specular.dds'

['dependencies.uuid']
Albedo = 'f48510e9-3823-4bbe-bb08-6129a407e631'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = '4caedc89-e4aa-4dcd-bd2d-efebb11898b4'
Normal = '494558bb-2e2c-444d-ac8d-d465e8bfa37a'
Roughness = '4caedc89-e4aa-4dcd-bd2d-efebb11898b4'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0