Name = 'M_Trim_Inst.toml'
Type = 'Material'
UUID = '18ca2d6b-f635-4842-aaff-e317a233bdc3'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Trim_Inst_0_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Trim_Inst_0_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Trim_Inst_0_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Trim_Inst_0_Specular.dds'

['dependencies.uuid']
Albedo = 'e4c156a5-a5bc-46cc-af7f-30df5cba4d0e'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = '8440cf18-6b6b-4d43-b34b-59609c144c7a'
Normal = '80cbd203-6416-4fe4-998b-1c7ab3c82c06'
Roughness = '8440cf18-6b6b-4d43-b34b-59609c144c7a'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0