Name = 'M_Tree_Branches_Inst.DoubleSided.toml'
Type = 'Material'
UUID = '6f950ca5-d656-4407-907a-6aae6258d4ea'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Tree_Branches_Inst_0_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Tree_Branches_Inst_0_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Tree_Branches_Inst_0_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/M_Tree_Branches_Inst_0_Specular.dds'

['dependencies.uuid']
Albedo = 'e1022255-400a-458f-bb62-26babd2ac1a6'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = '33587ded-5a87-464c-a8c0-6147417e44af'
Normal = '24dcf8cc-975d-4863-8189-6c99c2dec656'
Roughness = '33587ded-5a87-464c-a8c0-6147417e44af'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0