Name = 'Material__25.toml'
Type = 'Material'
UUID = 'a609bbf1-668f-41b1-9c1d-20d319cbe932'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/lion.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/lion_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '751e1969-e7a1-49bb-acab-14de738bccaf'
AmbientOcclusion = 'd516c30e-1a00-4332-93a7-00842791a762'
Metallic = '168f340c-4a48-4262-a73a-f0cd35439a59'
Normal = '641ab63c-3352-4fcf-a1c6-3c5aaedd3345'
Roughness = '2481bd11-a2f0-40e4-8d00-80ecd6eaa291'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0