Name = 'Material__298.toml'
Type = 'Material'
UUID = 'af349fa6-9530-4aac-ae03-6c9ee4a0a6e1'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/background.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/background_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '794adff7-1971-4b65-be66-7c9c5b8a9aeb'
AmbientOcclusion = '443c3376-43fb-45fa-ac7b-c8254e6e3fe1'
Metallic = '9fe7c8ff-a6e7-4837-882d-99ac1a2a98be'
Normal = 'eea2537b-4590-42c9-8697-5971ded3dfb8'
Roughness = '429045a2-9012-4811-8b0b-834064d64f89'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0