Name = 'Material__25.toml'
Type = 'Material'
UUID = '5c5eeb8b-d750-4008-b7dd-a2df5ad6a3e7'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/lion.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/lion_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = 'a11aedc8-22ec-419c-a387-ff0e5f6608b0'
AmbientOcclusion = '7c648b0f-3974-4e17-b932-86b547710e27'
Metallic = 'b126a381-c13c-4f1e-b73e-fd8853d93ba3'
Normal = '5b0a1cfd-5e36-4b1e-9298-fc1e4c3970a3'
Roughness = 'be8b05b1-b26a-4ad4-8f4a-f228049a7bf9'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0