Name = 'Material__298.toml'
Type = 'Material'
UUID = '29c700bc-e7bf-4bb5-b287-fcd62952a74f'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/background.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/background_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = 'b1311a97-fa81-434f-9387-6d723cb1f211'
AmbientOcclusion = '7c648b0f-3974-4e17-b932-86b547710e27'
Metallic = 'b126a381-c13c-4f1e-b73e-fd8853d93ba3'
Normal = 'd97d0044-2fe6-4d5a-8832-bf7389a140d5'
Roughness = 'be8b05b1-b26a-4ad4-8f4a-f228049a7bf9'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0