Name = 'Material__298.toml'
Type = 'Material'
UUID = 'e19d3cb1-2b5b-4446-813c-c83d37d37e3b'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/background.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/background_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = 'e41ff8cf-83ff-45fa-942b-b39e111d9641'
AmbientOcclusion = 'e017429a-4f3d-484f-80e6-db3b467423cf'
Metallic = '917023cc-8912-406f-b4dd-b9f98b81e821'
Normal = '2d2a2811-e169-4f46-bd9f-544b6906034e'
Roughness = 'ae673f67-7b5e-4fb4-88a7-9c90a9f42169'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0