Name = 'roof.toml'
Type = 'Material'
UUID = '88a49908-004a-4319-be66-bbe5427d37eb'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_roof_diff.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/sponza_roof_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '39efa7c1-8f50-49ea-94d2-396f908f5f1f'
AmbientOcclusion = 'd516c30e-1a00-4332-93a7-00842791a762'
Metallic = '168f340c-4a48-4262-a73a-f0cd35439a59'
Normal = '7641cec9-c40b-4d71-9c69-becde843244c'
Roughness = '2481bd11-a2f0-40e4-8d00-80ecd6eaa291'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0