Name = 'Soul_Tree011M_Inst.DoubleSided.toml'
Type = 'Material'
UUID = 'c9e58b5e-de70-468c-bfff-9e64016cbf26'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/Soul_Tree011M_Inst_0_BaseColor.dds'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/Soul_Tree011M_Inst_0_Specular.dds'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/Soul_Tree011M_Inst_0_Normal.dds'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SunTemple/Textures/Soul_Tree011M_Inst_0_Specular.dds'

['dependencies.uuid']
Albedo = 'f5105654-3d37-42ac-ac42-2ab090debf96'
AmbientOcclusion = 'a7a69818-c628-464c-b485-f4fb1353baf5'
Metallic = '67ff1a10-c91c-40d0-bef5-3ee8a2d37efb'
Normal = '99b61c3d-ff40-45fc-9e43-6906be0c5e16'
Roughness = '67ff1a10-c91c-40d0-bef5-3ee8a2d37efb'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0