Name = 'vase.toml'
Type = 'Material'
UUID = 'a8a69fdb-4355-49d5-92f4-b2da43f63ac2'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/vase_dif.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/vase_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = '7d96a7b1-2711-4068-9b88-cdf6953e19c5'
AmbientOcclusion = 'e017429a-4f3d-484f-80e6-db3b467423cf'
Metallic = '917023cc-8912-406f-b4dd-b9f98b81e821'
Normal = '2c431205-6314-4ba7-a5eb-83dddb6c625c'
Roughness = 'ae673f67-7b5e-4fb4-88a7-9c90a9f42169'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0