Name = 'vase_hanging.toml'
Type = 'Material'
UUID = 'aae48a90-ddfc-40cd-ba24-52d2911e275b'

['dependencies.path']
Albedo = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/vase_hanging.tga'
AmbientOcclusion = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_ambient_occlusion.png'
Metallic = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_metallic.png'
Normal = 'P:/Projects/VS/Wiley/Wiley/Assets/Models/SponzaOld/textures/vase_hanging_ddn.tga'
Roughness = 'P:/Projects/VS/Wiley/Wiley/Assets/Default Textures/default_roughness.png'

['dependencies.uuid']
Albedo = 'de486f3f-b8f5-4e4a-b403-bfedbb35af7c'
AmbientOcclusion = 'fdbb43cf-82ac-489b-b38f-fa40b76aa7cc'
Metallic = '1bf2cae4-4cbe-4640-ac3b-ed83c31120d8'
Normal = '5bf45c8a-0af9-45ef-b89b-ebeb2237cce7'
Roughness = '1957f4f1-aa48-450b-b2d3-0b7894f55581'

['properties.albedo']
value = [ 1.0, 1.0, 1.0, 1.0 ]

['properties.ambient_occlusion']
channel = 'R'
value = 1.0

['properties.global']
scale = [ 1.0, 1.0 ]

['properties.metallic']
channel = 'R'
value = 1.0

['properties.normal']
value = 1.0

['properties.roughness']
channel = 'R'
value = 1.0